Fix file test and some links

diff --git a/test/install/01_simput b/test/install/01_simput
--- a/test/install/01_simput
+++ b/test/install/01_simput
@@ -4,15 +4,20 @@ source ./setup.sh || exit 1
 
 # Test script to verify a recent version of simput is available
 
-SIMPUT=$(which simputversion)
-
 # have simput?
 if [ -z "${SIMPUT}" ] ; then
-  echo "***error: No simput found in \$PATH!" >&2
+  echo "***error: No simput found in \$SIMPUT!" >&2
   exit 1
 fi
 
-VERSION=$("${SIMPUT}")
+SIMPUTVERSION=$(which simputversion)
+
+if [ -z "${SIMPUTVERSION}" ] ; then
+  echo "***error: No 'simputersion in \$PATH! Did you source the install script?"
+  exit 1
+fi
+
+VERSION=$("${SIMPUTVERSION}")
 
 set -- ${VERSION}
 VERSION="$3"
diff --git a/test/install/02_sixte b/test/install/02_sixte
--- a/test/install/02_sixte
+++ b/test/install/02_sixte
@@ -4,15 +4,20 @@ source ./setup.sh || exit 1
 
 # Test if valid sixte version is available
 
-SIXTE=$(which sixteversion)
-
 # have sixte?
 if [ -z "${SIXTE}" ] ; then
-  echo "***error: No sixte found in \$PATH!" >&2
+  echo "***error: No sixte found in \$SIXTE!" >&2
   exit 1
 fi
 
-VERSION=$("${SIXTE}")
+SIXTEVERSION=$(which sixteversion)
+
+if [ -z "${SIXTEVERSION}" ] ; then
+  echo "***error: No 'sixteversion' in \$PATH! Did you source the install script?"
+  exit 1
+fi
+
+VERSION=$("${SIXTEVERSION}")
 
 set -- ${VERSION}
 VERSION="$3"
